modLoader="javafml"
loaderVersion="[37,)" #mandatory
license="MIT"
issueTrackerURL="https://github.com/Flanks255/simplylight/issues" #optional
[[mods]] #mandatory
modId="simplylight" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Simply Light" #mandatory
logoFile="logo.png" #optional
credits="" #optional
authors="Flanks255" #optional
description='''Simple light, for a complicated world.'''
